---
- hosts: azurehosts
  gather_facts: no
  vars:
    db:
      name: "comeback"
      user: "comeback"
      password: "vhBjjaKYkzHwxl1VqKrzR7WIhl4vy8hq"
      host: "dpg-d05sbih5pdvs73embv6g-a.oregon-postgres.render.com"
      port: 5432

  tasks:
    - name: Insert admin user into users table (Render DB)
      community.postgresql.postgresql_query:
        db: "{{ db.name }}"
        login_user: "{{ db.user }}"
        login_password: "{{ db.password }}"
        login_host: "{{ db.host }}"
        port: "{{ db.port }}"
        query: >
          INSERT INTO users (id, username, email, password)
          VALUES (1, 'admin', 'admin@example.com', 'admin')
          ON CONFLICT (id) DO NOTHING;
      tags: [admin]

    - name: Link admin user to role_id 2 in user_roles
      community.postgresql.postgresql_query:
        db: "{{ db.name }}"
        login_user: "{{ db.user }}"
        login_password: "{{ db.password }}"
        login_host: "{{ db.host }}"
        port: "{{ db.port }}"
        query: >
          INSERT INTO user_roles (user_id, role_id)
          VALUES (1, 2)
          ON CONFLICT DO NOTHING;
      tags: [admin]
