- hosts: all
  become: yes
  vars:
    appdir: "/home/azureuser/spring"
    branch: "main"

  pre_tasks:
    - name: Install Java and Maven
      apt:
        name:
          - openjdk-21-jdk
          - maven
        state: present
        update_cache: yes

  tasks:
    - name: Debug appdir
      ansible.builtin.debug:
        msg: "appdir {{ appdir }}"

    - name: Clone the Spring repository
      git:
        repo: "https://kotou13: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@github.com/kotou13/omada30.git"
        dest: "{{ appdir }}"
        version: "{{ branch }}"
        force: yes
      tags:
        - clone

    - name: Ensure correct ownership of the app directory
      file:
        path: "{{ appdir }}"
        owner: azureuser
        group: azureuser
        recurse: yes

    - name: Build the Spring application using system Maven
      command: mvn package -Dmaven.test.skip
      args:
        chdir: "{{ appdir }}"
      become_user: azureuser

    - name: Run the Spring application
      command: java -jar target/crowdfunding-0.0.1-SNAPSHOT.jar
      args:
        chdir: "{{ appdir }}"
      become_user: azureuser
























    